#!/usr/bin/env python3
"""
Research Coordinator - Manages parallel news research agents
Simpler PoC version that spawns agents via subprocess
"""

import json
import subprocess
import sys
from pathlib import Path
from datetime import datetime
from typing import List, Dict, Any
import time

class ResearchCoordinator:
    """Coordinates parallel research across multiple agents"""

    def __init__(self, base_dir: str = "/workspace/group/nanoclaw-skills/news-briefing"):
        self.base_dir = Path(base_dir)
        self.agents_dir = self.base_dir / "agents"
        self.results_dir = self.base_dir / "agents" / "results"
        self.results_dir.mkdir(parents=True, exist_ok=True)

    def load_research_tasks(self) -> List[Dict[str, Any]]:
        """Load research tasks generated by orchestrator"""
        tasks_file = self.agents_dir / "research_tasks.json"
        with open(tasks_file, 'r') as f:
            return json.load(f)

    def save_agent_prompt(self, task: Dict[str, Any]) -> str:
        """Save individual agent prompt to file"""
        task_id = task['task_id']
        prompt_file = self.agents_dir / f"prompt_{task_id}.txt"

        with open(prompt_file, 'w') as f:
            f.write(task['agent_prompt'])

        return str(prompt_file)

    def execute_research_parallel(self, tasks: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """
        Execute research tasks in parallel using Claude agents
        For PoC: We'll use a simpler approach - spawn tasks sequentially but design for parallel
        """
        results = []

        print(f"\n🤖 Spawning {len(tasks)} research agents...")

        for i, task in enumerate(tasks, 1):
            print(f"\n   Agent {i}/{len(tasks)}: {task['category']}")
            print(f"   Topics: {len(task['topics'])}")

            # Save the research result marker
            result_file = self.results_dir / f"result_{task['task_id']}.json"

            # For PoC, we'll create a command that can be executed
            # In production, this would use TeamCreate to spawn parallel agents
            agent_instruction = self._create_agent_instruction(task, result_file)

            print(f"   📝 Agent instruction ready")
            print(f"   💾 Will save to: {result_file.name}")

            results.append({
                "task_id": task['task_id'],
                "category": task['category'],
                "result_file": str(result_file),
                "agent_instruction": agent_instruction,
                "status": "ready"
            })

        return results

    def _create_agent_instruction(self, task: Dict[str, Any], result_file: Path) -> str:
        """Create instruction for Claude agent to execute"""

        instruction = f"""RESEARCH AGENT TASK: {task['category'].upper()}

Execute news research for the following topics:

"""
        for i, topic in enumerate(task['topics'], 1):
            instruction += f"{i}. {topic}\n"

        instruction += f"""

INSTRUCTIONS:
1. Use WebSearch tool to find recent articles (last 24 hours) for each topic
2. Focus on credible sources (major news outlets, tech blogs, official announcements)
3. Find 3-5 most important/relevant stories across all topics
4. For each article found:
   - Extract: title, summary (2-3 sentences), impact/why it matters, source URL, publication date, source name
   - Rate relevance: 1-10 score

5. Identify key trends across the articles
6. Note any expected news that didn't happen

OUTPUT FORMAT:
Save your results as JSON to: {result_file}

JSON Structure:
{{
  "category": "{task['category']}",
  "research_date": "{datetime.now().strftime('%Y-%m-%d')}",
  "articles": [
    {{
      "title": "Article headline",
      "summary": "2-3 sentence summary of what happened",
      "impact": "Why this matters / significance",
      "url": "Full source URL",
      "published": "YYYY-MM-DD HH:MM:SS",
      "source": "Publication name",
      "relevance_score": 8
    }}
  ],
  "key_trends": ["trend 1", "trend 2"],
  "notable_absence": "Any expected news that didn't materialize"
}}

PRIORITY: Find the most impactful, recent news. Quality over quantity.
"""
        return instruction

    def collect_results(self, result_markers: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Collect results from all research agents"""
        results = []

        print(f"\n📥 Collecting results from {len(result_markers)} agents...")

        for marker in result_markers:
            result_file = Path(marker['result_file'])

            if result_file.exists():
                try:
                    with open(result_file, 'r') as f:
                        result_data = json.load(f)

                    results.append(result_data)
                    print(f"   ✓ {marker['category']}: {len(result_data.get('articles', []))} articles")
                except Exception as e:
                    print(f"   ✗ {marker['category']}: Error reading result - {e}")
            else:
                print(f"   ⏳ {marker['category']}: Result not ready yet")

        return results

    def save_compiled_results(self, results: List[Dict[str, Any]]) -> str:
        """Save all compiled results"""
        output_file = self.results_dir / f"compiled_{datetime.now().strftime('%Y%m%d_%H%M%S')}.json"

        compiled = {
            "timestamp": datetime.now().isoformat(),
            "total_categories": len(results),
            "total_articles": sum(len(r.get('articles', [])) for r in results),
            "results": results
        }

        with open(output_file, 'w') as f:
            json.dump(compiled, f, indent=2)

        return str(output_file)


def main():
    """Main entry point"""
    coordinator = ResearchCoordinator()

    print("🔬 Research Coordinator - News Briefing System")
    print("=" * 60)

    # Load tasks
    print("\n📋 Loading research tasks...")
    tasks = coordinator.load_research_tasks()
    print(f"   ✓ Loaded {len(tasks)} tasks")

    # Execute research (prepare agents)
    result_markers = coordinator.execute_research_parallel(tasks)

    print(f"\n✅ Research coordination complete!")
    print(f"   {len(result_markers)} agents ready to execute")
    print(f"\n💡 Next step: Execute the research agents")
    print(f"   Each agent will search the web and save results to agents/results/")

    # Save agent execution plan
    execution_plan_file = coordinator.agents_dir / "execution_plan.json"
    with open(execution_plan_file, 'w') as f:
        json.dump(result_markers, f, indent=2)

    print(f"\n📄 Execution plan saved to: {execution_plan_file}")


if __name__ == "__main__":
    main()
