-- Email pre-router bootstrap.
--
-- Idempotent. Run from repo root:
--   sqlite3 data/v2.db < scripts/email-pre-router-bootstrap.sql
--
-- What this does:
--   1. Create the calendar-watch agent_group (if missing) — its persona at
--      groups/calendar-watch/CLAUDE.local.md handles invites/declines/#cal
--      notes via gog calendar.
--   2. Pre-wire `email:cal` (the platformId the pre-router emits for any
--      calendar inbound) → calendar-watch. So the first calendar invite that
--      lands won't get stuck in the channel-request approval flow.
--   3. Wire the four pending Telegram approval cards we walked through:
--        * customer-success-advisor@zoom.us  → DENY (auto-archive)
--        * no-reply@zoom.us (Zoom security/transactional codes) → DENY
--          (we'll add a sender-policy filter that auto-archives these
--          without an approval card; the existing pending row gets denied
--          here so Telegram stops pinging)
--        * noreply-marketplace@zoom.us → wire to existing `zoom` agent
--        * drive-shares-dm-noreply@google.com → wire to existing `google`
--          agent
--      And delete the corresponding pending_channel_approvals rows so
--      Telegram stops asking.

BEGIN;

-- ── 1. calendar-watch agent_group ───────────────────────────────────────────

INSERT OR IGNORE INTO agent_groups (id, name, folder, agent_provider, created_at)
VALUES ('ag-1778120000000-cal01', 'jibot', 'calendar-watch', NULL, datetime('now'));

-- ── 2. email:cal pre-wired to calendar-watch ───────────────────────────────

INSERT OR IGNORE INTO messaging_groups (
  id, channel_type, platform_id, name, is_group,
  unknown_sender_policy, created_at
) VALUES (
  'mg-email-cal',
  'email',
  'email:cal',
  'Calendar (pre-routed)',
  0,
  'strict',
  datetime('now')
);

INSERT OR IGNORE INTO messaging_group_agents (
  id, messaging_group_id, agent_group_id,
  session_mode, priority, created_at,
  engage_mode, engage_pattern, sender_scope, ignored_message_policy
) VALUES (
  'mga-email-cal',
  'mg-email-cal',
  'ag-1778120000000-cal01',
  'shared', 0, datetime('now'),
  'pattern', '.', 'all', NULL
);

-- ── 3a. Wire noreply-marketplace@zoom.us → zoom (existing agent) ────────────

UPDATE pending_channel_approvals SET created_at = created_at
WHERE messaging_group_id = 'mg-1778117364000-marketplace';
-- (no-op preserving the existing pending row's id; the actual id was
--  auto-generated by the router. We look it up by platform_id below.)

-- Look up the actual messaging_group_id and insert the wiring.
INSERT OR IGNORE INTO messaging_group_agents (
  id, messaging_group_id, agent_group_id,
  session_mode, priority, created_at,
  engage_mode, engage_pattern, sender_scope, ignored_message_policy
) SELECT
  'mga-' || mg.id,
  mg.id,
  (SELECT id FROM agent_groups WHERE folder = 'zoom'),
  'shared', 0, datetime('now'),
  'pattern', '.', 'all', NULL
FROM messaging_groups mg
WHERE mg.channel_type = 'email'
  AND mg.platform_id = 'email:jibot@ito.com:noreply-marketplace@zoom.us';

DELETE FROM pending_channel_approvals
WHERE messaging_group_id IN (
  SELECT id FROM messaging_groups
  WHERE channel_type = 'email' AND platform_id = 'email:jibot@ito.com:noreply-marketplace@zoom.us'
);

-- ── 3b. Wire drive-shares-dm-noreply@google.com → google ───────────────────

INSERT OR IGNORE INTO messaging_group_agents (
  id, messaging_group_id, agent_group_id,
  session_mode, priority, created_at,
  engage_mode, engage_pattern, sender_scope, ignored_message_policy
) SELECT
  'mga-' || mg.id,
  mg.id,
  (SELECT id FROM agent_groups WHERE folder = 'google'),
  'shared', 0, datetime('now'),
  'pattern', '.', 'all', NULL
FROM messaging_groups mg
WHERE mg.channel_type = 'email'
  AND mg.platform_id = 'email:jibot@ito.com:drive-shares-dm-noreply@google.com';

DELETE FROM pending_channel_approvals
WHERE messaging_group_id IN (
  SELECT id FROM messaging_groups
  WHERE channel_type = 'email' AND platform_id = 'email:jibot@ito.com:drive-shares-dm-noreply@google.com'
);

-- ── 3c. Deny customer-success-advisor@zoom.us (promotional) ─────────────────

UPDATE messaging_groups
SET denied_at = datetime('now')
WHERE channel_type = 'email'
  AND platform_id = 'email:jibot@ito.com:customer-success-advisor@zoom.us';

DELETE FROM pending_channel_approvals
WHERE messaging_group_id IN (
  SELECT id FROM messaging_groups
  WHERE channel_type = 'email' AND platform_id = 'email:jibot@ito.com:customer-success-advisor@zoom.us'
);

-- ── 3d. Deny no-reply@zoom.us (transactional codes — agent can't act) ──────

UPDATE messaging_groups
SET denied_at = datetime('now')
WHERE channel_type = 'email'
  AND platform_id = 'email:jibot@ito.com:no-reply@zoom.us';

DELETE FROM pending_channel_approvals
WHERE messaging_group_id IN (
  SELECT id FROM messaging_groups
  WHERE channel_type = 'email' AND platform_id = 'email:jibot@ito.com:no-reply@zoom.us'
);

COMMIT;

-- Verify
SELECT 'agent_groups (email-related)' AS section, '' AS detail
UNION ALL
SELECT folder, id FROM agent_groups
WHERE folder LIKE 'email%' OR folder IN ('calendar-watch','google','google-cloud','zoom')
ORDER BY 1;

SELECT '--- email wirings ---' AS section, '' AS detail
UNION ALL
SELECT mg.platform_id || (CASE WHEN mg.denied_at IS NOT NULL THEN ' [DENIED]' ELSE '' END),
       COALESCE(ag.folder, '(no agent)')
FROM messaging_groups mg
LEFT JOIN messaging_group_agents mga ON mga.messaging_group_id = mg.id
LEFT JOIN agent_groups ag ON ag.id = mga.agent_group_id
WHERE mg.channel_type = 'email'
ORDER BY 1;

SELECT '--- pending email approvals ---' AS section, '' AS detail
UNION ALL
SELECT mg.platform_id, pca.title
FROM pending_channel_approvals pca
JOIN messaging_groups mg ON mg.id = pca.messaging_group_id
WHERE mg.channel_type = 'email';
