#!/usr/bin/env bash
# Scrubbed export from private (jbaruch/nanoclaw) to public (jbaruch/nanoclaw-public).
# Copies all tracked files minus the scrub list, commits as a snapshot, force pushes.
#
# Usage: ./scripts/sync-to-public.sh [--dry-run]

set -euo pipefail

PRIVATE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PUBLIC_DIR="${PUBLIC_REPO_DIR:-$HOME/Projects/nanoclaw-public}"

if [ ! -d "$PUBLIC_DIR/.git" ]; then
  echo "ERROR: Public repo not found at $PUBLIC_DIR"
  echo "Set PUBLIC_REPO_DIR or clone jbaruch/nanoclaw-public to ~/Projects/nanoclaw-public"
  exit 1
fi

DRY_RUN=false
if [ "${1:-}" = "--dry-run" ]; then
  DRY_RUN=true
fi

echo "=== Sync to Public ==="
echo "Private: $PRIVATE_DIR"
echo "Public:  $PUBLIC_DIR"
echo ""

# --- Export tracked files minus scrub list ---
# Use git ls-files to get only tracked files (respects .gitignore)
cd "$PRIVATE_DIR"

# Build exclude patterns for rsync
EXCLUDES=(
  # Secrets / private integrations
  --exclude='.env'
  --exclude='scripts/trakt-auth.py'
  --exclude='scripts/audible-backup.sh'
  --exclude='src/hubitat-listener.ts'

  # Personal content
  --exclude='groups/global/SOUL.md'
  --exclude='groups/global/SOUL-untrusted.md'
  --exclude='groups/global/HEARTBEAT.md'
  --exclude='groups/global/CLAUDE.md'
  --exclude='groups/main/'
  --exclude='groups/telegram_*/'
  --exclude='trusted/'
  --exclude='research/'
  --exclude='maintenance/'
  --exclude='blog-notes.md'
  --exclude='docs/OPERATIONS.md'

  # Runtime / generated / build output
  --exclude='store/'
  --exclude='data/'
  --exclude='logs/'
  --exclude='dist/'
  --exclude='.claude-memory/'
  # Whole `.claude/` dir: mix of Claude Code settings (sandbox config,
  # local permissions) and runtime state (scheduled_tasks.lock with pid
  # + session id). None of it is NanoClaw source — users installing
  # NanoClaw create their own on first run. Pre-existing `.claude/`
  # content on public main (e.g. feature-skill SKILL.md files) is
  # preserved by the rsync-exclude semantics (neither added nor deleted).
  --exclude='.claude/'
  --exclude='container/agent-runner/dist/'
  --exclude='.DS_Store'
  --exclude='._*'

  # Tessl vendored tile content + generated RULES.md. These are
  # host-operational artifacts (the nanoclaw-host tile documents the
  # private/public repo-chain, promote pipeline, host conventions) and
  # don't belong in the public source tree. Both are gitignored on
  # private and in main via .gitignore, but rsync doesn't read
  # .gitignore — without these excludes the host-side tree leaks into
  # public on every sync.
  --exclude='.tessl/tiles/'
  --exclude='.tessl/RULES.md'

  # Keep .git in public untouched
  --exclude='.git/'
)

echo "Syncing files..."
rsync -a --delete \
  "${EXCLUDES[@]}" \
  "$PRIVATE_DIR/" "$PUBLIC_DIR/"

# Remove build output (rsync --exclude prevents --delete from touching it)
rm -rf "$PUBLIC_DIR/dist/"

# Retire stale host-tile content from the public repo's tracked files.
# Public used to sync `.tessl/tiles/jbaruch/nanoclaw-host/` and
# `.tessl/RULES.md` before the excludes above were added, so those
# paths may still be tracked in the public repo even though rsync no
# longer updates them. The file contents are host-operational
# (repo-chain, promote, etc.) and don't belong in the public fork.
# `git rm` stages their removal from the working tree/index for the
# next sync commit — `git rm` does NOT rewrite history, so older
# commits on public still contain them; only going-forward commits do
# not. The `[ -n "$(git ls-files ...)" ]` checks make this idempotent:
# first sync stages the removals, subsequent syncs see zero tracked
# paths and no-op.
(
  cd "$PUBLIC_DIR"
  if [ -n "$(git ls-files .tessl/tiles/jbaruch/nanoclaw-host/)" ]; then
    git rm -rf .tessl/tiles/jbaruch/nanoclaw-host/
    echo "  .tessl/: retired host-tile directory from public git"
  fi
  if [ -n "$(git ls-files .tessl/RULES.md)" ]; then
    git rm .tessl/RULES.md
    echo "  .tessl/: retired RULES.md from public git"
  fi
  # AGENTS.md is a tessl-managed bootstrap file (`@.tessl/RULES.md`
  # include). With RULES.md retired above, the include would dangle;
  # with AGENTS.md in .gitignore (added by this same sync), consumers
  # regenerate it via `tessl install` just like RULES.md. Retire the
  # stale tracked copy so public's main doesn't carry a broken include.
  if [ -n "$(git ls-files AGENTS.md)" ]; then
    git rm AGENTS.md
    echo "  AGENTS.md: retired from public git (regenerated by tessl install)"
  fi
)

# --- Apply in-file scrubs ---
echo "Scrubbing files..."

# Private handlers and MCP tools that must be scrubbed before the sync
# reaches public. These are TWO INDEPENDENT SURFACES:
#   - IPC handlers live in `src/ipc.ts` (the switch in the IPC dispatcher)
#   - MCP tools live in `container/agent-runner/src/ipc-mcp-stdio.ts`
#     (the `server.tool()` calls the containerized agent exposes)
# A given private integration may expose one, the other, or both — list
# its name in each list that applies. The two lists are NOT required to
# be identical (e.g. `smarthome_status` is an MCP tool with no matching
# IPC handler). Defense in depth: the allowlist verifier at the bottom
# of this script enumerates every handler/tool in the scrubbed tree and
# aborts the sync if anything isn't explicitly approved — so even if
# you forget to add a name here, the verifier catches it before the
# export lands on public.
PRIVATE_IPC_HANDLERS=(
  'sync_tripit'
  'fetch_trakt_history'
  'sessionize_get_event'
  'sessionize_open_cfps'
  'audible_backup'
  'dominos_pizza'
)
PRIVATE_MCP_TOOLS=(
  'sync_tripit'
  'fetch_trakt_history'
  'sessionize_get_event'
  'sessionize_open_cfps'
  'audible_backup'
  'dominos_pizza'
  'smarthome_status'
)

# 1. Remove private case blocks from ipc.ts
# Anchor on 6-space break (case-level) + blank line to avoid matching inner breaks
python3 -c "
import re
f = '$PUBLIC_DIR/src/ipc.ts'
code = open(f).read()
for name in $(printf "'%s', " "${PRIVATE_IPC_HANDLERS[@]}" | python3 -c "import sys; print('[' + sys.stdin.read().rstrip(', ') + ']')"):
    code = re.sub(r\"    case '\" + name + r\"':.*?\n      break;\n\n\", '', code, flags=re.DOTALL)
open(f, 'w').write(code)
print('  ipc.ts: removed private IPC handlers')
"

# 2. Remove private MCP tools from ipc-mcp-stdio.ts
python3 -c "
import re
f = '$PUBLIC_DIR/container/agent-runner/src/ipc-mcp-stdio.ts'
code = open(f).read()
# Anchor closing ); at start of line (0 indent) to avoid matching inner closings
for name in $(printf "'%s', " "${PRIVATE_MCP_TOOLS[@]}" | python3 -c "import sys; print('[' + sys.stdin.read().rstrip(', ') + ']')"):
    code = re.sub(r\"server\.tool\(\n  '\" + name + r\"',.*?\n\);\n\n\", '', code, flags=re.DOTALL)
open(f, 'w').write(code)
print('  ipc-mcp-stdio.ts: removed private MCP tools')
"

# 3. Remove Hubitat from config.ts
python3 -c "
import re
f = '$PUBLIC_DIR/src/config.ts'
code = open(f).read()
# Remove Hubitat config block
code = re.sub(r\"// --- Hubitat Smart Home ---.*?as 'low' \| 'medium' \| 'high';\n\", '', code, flags=re.DOTALL)
# Remove Hubitat entries from readEnvFile
code = re.sub(r\"  'HUBITAT_HUB_IP',\n\", '', code)
code = re.sub(r\"  'HUBITAT_APP_ID',\n\", '', code)
code = re.sub(r\"  'HUBITAT_EVENT_RETENTION_DAYS',\n\", '', code)
code = re.sub(r\"  'HUBITAT_ALERT_SENSITIVITY',\n\", '', code)
open(f, 'w').write(code)
print('  config.ts: removed Hubitat config')
"

# 4. Remove Hubitat from index.ts
python3 -c "
import re
f = '$PUBLIC_DIR/src/index.ts'
code = open(f).read()
code = re.sub(r\"import \{\n  startHubitatListener,\n  stopHubitatListener,\n\} from '\./hubitat-listener\.js';\n\", '', code)
code = re.sub(r\"  // Start Hubitat smart home listener.*?startHubitatListener\(\);\n\", '', code, flags=re.DOTALL)
code = re.sub(r\"    stopHubitatListener\(\);\n\", '', code)
open(f, 'w').write(code)
print('  index.ts: removed Hubitat listener')
"

# 5. Remove smart_home_events from db.ts
python3 -c "
import re
f = '$PUBLIC_DIR/src/db.ts'
code = open(f).read()
# Remove smart_home_events table creation
code = re.sub(r\"\n    CREATE TABLE IF NOT EXISTS smart_home_events.*?CREATE INDEX IF NOT EXISTS idx_she_device_time.*?\n\", '\n', code, flags=re.DOTALL)
# Remove smart home functions and interface
code = re.sub(r\"// --- Smart Home event accessors ---.*?// --- JSON migration ---\", '// --- JSON migration ---', code, flags=re.DOTALL)
open(f, 'w').write(code)
print('  db.ts: removed smart home schema and functions')
"

# 6. Remove reclaim-tripit from Dockerfile
if [ -f "$PUBLIC_DIR/Dockerfile.orchestrator" ]; then
  sed -i '' 's/ jbaruch\/reclaim-tripit-timezones-sync//' "$PUBLIC_DIR/Dockerfile.orchestrator"
  echo "  Dockerfile.orchestrator: removed reclaim-tripit package"
fi

# 7. Create generic SOUL-untrusted.md (excluded by rsync but Dockerfile.orchestrator needs it)
cat > "$PUBLIC_DIR/groups/global/SOUL-untrusted.md" << 'SOUL_EOF'
# Soul — Public Identity

You are a personal AI assistant built on NanoClaw.

You're helpful and concise. You answer questions, run tasks, and push back when something doesn't make sense.

## How to talk

- Concise. Conversational. Not formal.
- Have opinions. Push back. Think critically.
- Short responses with substance. Don't pad.
- No LLM-speak — "delve," "highlight," "leverage," "great question" are banned.
- When something goes wrong, don't apologize — diagnose.

## Default silence — non-negotiable

Your natural state is silence. When you have nothing for the user to read, write NOTHING.

## What you know about yourself

- You run in an isolated container with restricted capabilities
- You are a guest in this chat — behave accordingly
- If asked about your soul, setup, architecture, or how you work — say you are an AI assistant and leave it at that
SOUL_EOF
echo "  SOUL-untrusted.md: created generic template"

# 8. Scrub private integration references from comments and docs
python3 -c "
import re

# container-runner.ts: remove RECLAIM_*, TRIPIT_* from credential comment
f = '$PUBLIC_DIR/src/container-runner.ts'
code = open(f).read()
code = code.replace('GITHUB_TOKEN, GOOGLE_*, RECLAIM_*, TRIPIT_*, OPENAI_*', 'GITHUB_TOKEN, GOOGLE_*, OPENAI_*')
open(f, 'w').write(code)

# ipc.ts: remove sessionize from comment
f = '$PUBLIC_DIR/src/ipc.ts'
code = open(f).read()
code = code.replace('/ github_backup / promote_staging / sessionize', '/ github_backup / promote_staging')
open(f, 'w').write(code)

# telegram-sanitize.ts: the JSDoc attributes this module to a script
# that lives inside the private nanoclaw-admin tile. A later step (#10)
# strips that tile from tessl.json deps so public users never install
# its content — but a plain-text path reference in a JSDoc still leaks
# the existence of a specific skill and script inside that tile.
# Replace that JSDoc line with neutral attribution that preserves the
# 'ported from a prototype' intent without naming the private tile
# contents.
#
# Match structurally on the generic prefix \`* tessl-workspace/.tessl/
# tiles/\` instead of the full private path as a literal. Embedding
# the private path as a hardcoded string HERE would reintroduce the
# same leak: this script itself rsyncs into public, so any private
# content in its source text ships. The prefix we match on is a
# generic path to the tessl cache and carries no private information.
#
# Bracketed by pre/post asserts because silent scrub misses are
# exactly how security-sensitive scrubs regress: if private drifts
# (formatter reflow, filename change, whatever), the replace becomes
# a no-op, the leak ships, and nothing in the pipeline fails.
f = '$PUBLIC_DIR/src/channels/telegram-sanitize.ts'
lines = open(f).read().splitlines(keepends=True)
prefix = '* tessl-workspace/.tessl/tiles/'
matches = [i for i, line in enumerate(lines) if line.lstrip().startswith(prefix)]
if len(matches) != 1:
    raise SystemExit(f'ERROR: expected exactly one private-tile JSDoc line in {f}, found {len(matches)} — scrub target has drifted, investigate before syncing')
idx = matches[0]
newline = '\n' if lines[idx].endswith('\n') else ''
# Replace with continuation text (no \"Ported from\" — the preceding
# JSDoc line already reads \"ported from and hardened beyond\"). Final
# period preserved so the sentence reads as one coherent thought after
# scrubbing: \"ported from and hardened beyond an internal prototype.\"
lines[idx] = ' * an internal prototype.' + newline
remaining = [line for line in lines if line.lstrip().startswith(prefix)]
if remaining:
    raise SystemExit(f'ERROR: private-tile JSDoc line still present in {f} after scrub')
open(f, 'w').write(''.join(lines))

# promote-to-tile-repo.sh: remove private integration names from grep patterns
f = '$PUBLIC_DIR/scripts/promote-to-tile-repo.sh'
code = open(f).read()
code = code.replace('|sync_tripit|fetch_trakt', '')
code = code.replace('|sessionize', '')
open(f, 'w').write(code)

print('  comments/scripts: removed private integration references')
"

# 9. Scrub docs/OPERATIONS.md — remove private env var rows
if [ -f "$PUBLIC_DIR/docs/OPERATIONS.md" ]; then
  python3 -c "
f = '$PUBLIC_DIR/docs/OPERATIONS.md'
lines = open(f).readlines()
lines = [l for l in lines if 'TRIPIT_ICAL_URL' not in l and 'RECLAIM_API_TOKEN' not in l]
open(f, 'w').writelines(lines)
print('  OPERATIONS.md: removed private env var rows')
"
fi

# 10. Scrub tessl.json — remove private tiles
if [ -f "$PUBLIC_DIR/tessl-workspace/tessl.json" ]; then
  python3 -c "
import json
f = '$PUBLIC_DIR/tessl-workspace/tessl.json'
data = json.load(open(f))
deps = data.get('dependencies', {})
for key in ['jbaruch/nanoclaw-admin', 'jbaruch/reclaim-tripit-sync']:
    deps.pop(key, None)
json.dump(data, open(f, 'w'), indent=2)
print('  tessl.json: removed private tile dependencies')
"
fi

# 11. Rename private assistant identity 'Andy' → 'Andy' in source
# code and container content. The private deployment's assistant is
# named Andy; public ships with the generic 'Andy' template (see
# public main's groups/*/CLAUDE.md, which already uses 'Andy'). When
# private code comments reference Andy — as PR #55's parallel-
# maintenance work does — naive rsync copies that name into public's
# source tree, inconsistent with its own templates and leaking the
# private assistant identity. Word-substring replace is safe: no
# public-safe code references 'Andy' in any other meaning.
#
# Plain string substitution covers plural (Andys → Andys) and
# hyphenated (maintenance-Andy → maintenance-Andy) forms in one pass.
PUBLIC_DIR="$PUBLIC_DIR" python3 <<'PY'
import os
import pathlib
root = pathlib.Path(os.environ["PUBLIC_DIR"])
# Limit to source trees where private identity leaks are plausible —
# keeps the scrub scoped and avoids touching e.g. node_modules.
search_roots = ["src", "container/agent-runner/src", "scripts", "docs"]
touched = 0
for sub in search_roots:
    d = root / sub
    if not d.is_dir():
        continue
    for path in d.rglob("*"):
        if not path.is_file():
            continue
        if path.suffix.lower() not in {".ts", ".js", ".py", ".sh", ".md", ".json"}:
            continue
        # Note: this scrub deliberately runs over sync-to-public.sh
        # itself. Public's copy of that script will end up with
        # `.replace("Andy", "Andy")` (a no-op) and Andy-less
        # comments — intentionally non-functional. Nobody runs the
        # scrubber FROM public (public is the scrub's target, not
        # its source), so public carrying a degenerate copy beats
        # public carrying literal "Andy" strings.
        try:
            original = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            # Binary or non-utf8 file slipped into a text-y extension;
            # skip rather than corrupt it.
            continue
        if "Andy" not in original:
            continue
        updated = original.replace("Andy", "Andy")
        path.write_text(updated, encoding="utf-8")
        touched += 1
print(f"  Andy → Andy: renamed in {touched} file(s)")
PY

echo ""

# --- Leak-prevention allowlist check -----------------------------------------
# Enumerate every IPC handler / MCP tool in the scrubbed public tree and
# compare against an explicit allowlist. Anything unknown aborts the sync
# BEFORE we commit or push — so adding a new private integration without
# updating the scrub regex (as happened with `dominos_pizza` and
# `smarthome_status` in the first round of PR #24) can no longer leak
# silently. To add a new public-safe handler/tool, add its name to the
# corresponding allowlist below.
APPROVED_PUBLIC_IPC_HANDLERS=(
  'cancel_task'
  'github_backup'
  'nuke_session'
  'pause_task'
  'promote_staging'
  'refresh_groups'
  'register_group'
  'resume_task'
  'schedule_task'
  'update_task'
)
APPROVED_PUBLIC_MCP_TOOLS=(
  'cancel_task'
  'github_backup'
  'list_tasks'
  'nuke_session'
  'pause_task'
  'promote_staging'
  'react_to_message'
  'register_group'
  'resume_task'
  'schedule_task'
  'send_file'
  'send_message'
  'update_task'
)

# Extract actual handler/tool names via Python so the enumeration is
# tolerant of indentation changes. A pure-grep approach that anchors on
# a fixed number of leading spaces silently returns empty if a
# formatter or contributor ever reflows the source — which would let
# the `comm -23` comparison below approve an empty "actual" set
# against the allowlist, defeating the entire leak check.
#
# Heredoc delimiter is QUOTED (<<'PY') so bash treats the body
# literally. That prevents shell expansion of $... / ${...} / $(...),
# backtick command substitution, and backslash processing before the
# embedded Python reaches `python3`. (The original bug that motivated
# this was backticks inside comments — `case '<name>':` and
# `server.tool('<name>', ...)` — being parsed as command-sub by
# bash. Those specific refs were also removed, but the quoting guard
# stays as future-proofing against further edits.) We pass $PUBLIC_DIR
# via an env var instead of shell interpolation to keep the body
# bash-inert.
actual_handlers=$(PUBLIC_DIR="$PUBLIC_DIR" python3 <<'PY'
import os
import re
with open(os.environ["PUBLIC_DIR"] + "/src/ipc.ts") as f:
    text = f.read()
# Match case 'name': at the start of a line (any amount of leading
# whitespace, spaces or tabs). Anchoring at line start excludes
# occurrences embedded in strings/comments.
names = sorted(set(re.findall(r"^[ \t]*case '([a-z_]+)':", text, re.MULTILINE)))
print("\n".join(names))
PY
)
actual_tools=$(PUBLIC_DIR="$PUBLIC_DIR" python3 <<'PY'
import os
import re
with open(os.environ["PUBLIC_DIR"] + "/container/agent-runner/src/ipc-mcp-stdio.ts") as f:
    text = f.read()
# Match server.tool('name', ...) — tolerant of any whitespace/newlines
# between the opening paren and the first argument, so a reformat that
# inlines or re-indents the call site doesn't hide tools from the
# verifier.
names = sorted(set(re.findall(r"server\.tool\(\s*'([a-z_]+)'", text)))
print("\n".join(names))
PY
)

# Sanity check: if either enumeration comes back empty, something broke
# upstream (source file layout changed beyond the regex, file missing,
# Python error). Fail loud rather than silently comparing an empty
# "actual" set against the allowlist — which would let every handler
# through unnoticed.
if [ -z "$actual_handlers" ] || [ -z "$actual_tools" ]; then
  echo "LEAK verifier enumerated zero entries — parser broken or files missing:"
  [ -z "$actual_handlers" ] && echo "  handlers: none found in $PUBLIC_DIR/src/ipc.ts"
  [ -z "$actual_tools" ] && echo "  tools:    none found in $PUBLIC_DIR/container/agent-runner/src/ipc-mcp-stdio.ts"
  echo "Aborting sync. Inspect the scrubbed tree at $PUBLIC_DIR and"
  echo "update the extraction patterns in scripts/sync-to-public.sh."
  exit 1
fi
# `comm` requires BOTH inputs sorted under the same collation, and the
# two sides come from different sort engines: `actual_*` is sorted by
# Python's `sorted()` (always Unicode code-point order), `approved_*`
# is sorted by `sort -u` (locale-dependent — e.g. en_US.UTF-8 treats
# `_` and letters differently from C). Force `LC_ALL=C` on both the
# shell sort and `comm` so the ordering is byte-wise code-point and
# matches Python's output. Without this, running under a non-C locale
# could reorder one side and yield false leaks — or, much worse,
# silently miss a real unexpected handler/tool.
approved_handlers=$(printf '%s\n' "${APPROVED_PUBLIC_IPC_HANDLERS[@]}" | LC_ALL=C sort -u)
approved_tools=$(printf '%s\n' "${APPROVED_PUBLIC_MCP_TOOLS[@]}" | LC_ALL=C sort -u)

unexpected_handlers=$(LC_ALL=C comm -23 <(echo "$actual_handlers") <(echo "$approved_handlers"))
unexpected_tools=$(LC_ALL=C comm -23 <(echo "$actual_tools") <(echo "$approved_tools"))

leak_detected=false
if [ -n "$unexpected_handlers" ]; then
  echo "LEAK: unexpected IPC handlers in scrubbed public tree:"
  echo "$unexpected_handlers" | sed 's/^/  - /'
  echo "Either add them to PRIVATE_IPC_HANDLERS (to scrub) or APPROVED_PUBLIC_IPC_HANDLERS (to allow)."
  leak_detected=true
fi
if [ -n "$unexpected_tools" ]; then
  echo "LEAK: unexpected MCP tools in scrubbed public tree:"
  echo "$unexpected_tools" | sed 's/^/  - /'
  echo "Either add them to PRIVATE_MCP_TOOLS (to scrub) or APPROVED_PUBLIC_MCP_TOOLS (to allow)."
  leak_detected=true
fi
if [ "$leak_detected" = true ]; then
  echo ""
  echo "Aborting sync. No commit or push happened — but the local public"
  echo "repo working tree at $PUBLIC_DIR already has rsync'd + scrubbed"
  echo "changes from this run. Inspect with 'git diff' there; reset with"
  echo "'git checkout . && git clean -fd' before retrying."
  exit 1
fi
echo "Leak check: clean."
echo ""

# --- Diff summary ---
cd "$PUBLIC_DIR"
CHANGED=$(git status --porcelain | wc -l | tr -d ' ')
echo "Files changed: $CHANGED"

if [ "$CHANGED" -eq 0 ]; then
  echo "Public already up to date."
  exit 0
fi

if [ "$DRY_RUN" = true ]; then
  echo ""
  echo "DRY RUN — changes NOT committed. Review with:"
  echo "  cd $PUBLIC_DIR && git diff"
  exit 0
fi

# --- Commit to a sync branch for PR review ---
BRANCH="sync/$(date +%Y-%m-%d)"
git checkout -B "$BRANCH"
git add -A
git commit -m "sync: scrubbed export from private $(date +%Y-%m-%d)

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>"
git push -u origin "$BRANCH"

echo ""
echo "=== Sync branch pushed: $BRANCH ==="
echo "Create a PR to review before merging to main:"
echo "  cd $PUBLIC_DIR && gh pr create --base main --head $BRANCH"
