/**
 * Build-time metadata (git commit, build timestamp).
 * Generated by scripts/generate-build-info.js during build.
 */

import { execSync } from 'child_process';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

export interface BuildInfo {
  commit: string;
  commitShort: string;
  commitDate: string | null;
  branch: string;
  dirty: boolean;
  buildTime: string;
}

const __dirname = path.dirname(fileURLToPath(import.meta.url));

function loadBuildInfo(): BuildInfo {
  // Try loading from build-info.json (generated at build time)
  const jsonPath = path.join(__dirname, 'build-info.json');
  if (fs.existsSync(jsonPath)) {
    try {
      return JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
    } catch {
      // Fall through to defaults
    }
  }

  // Fallback for dev mode (tsx) — read git info directly
  try {
    const projectRoot = path.resolve(__dirname, '..');
    const exec = (cmd: string) =>
      execSync(cmd, { cwd: projectRoot, encoding: 'utf-8' }).trim();

    return {
      commit: exec('git rev-parse HEAD'),
      commitShort: exec('git rev-parse --short HEAD'),
      commitDate: exec('git log -1 --format=%cI'),
      branch: exec('git rev-parse --abbrev-ref HEAD'),
      dirty: exec('git status --porcelain') !== '',
      buildTime: new Date().toISOString(),
    };
  } catch {
    return {
      commit: 'unknown',
      commitShort: 'unknown',
      commitDate: null,
      branch: 'unknown',
      dirty: false,
      buildTime: new Date().toISOString(),
    };
  }
}

export const buildInfo = loadBuildInfo();

/** Short version string for logs: "abc1234" or "abc1234-dirty" */
export const versionTag = buildInfo.dirty
  ? `${buildInfo.commitShort}-dirty`
  : buildInfo.commitShort;
