/**
 * FAQ short-circuit — answer static questions without spawning a container.
 *
 * Saves the full container lifecycle cost (Docker startup + full LLM call)
 * for questions whose answers live entirely in the CLAUDE.md FAQ section.
 *
 * Conservative by design: only fires on clearly static questions (address,
 * payment, parking). Any booking intent signals pass through to the LLM.
 */

import fs from 'fs';
import path from 'path';
import { resolveGroupFolderPath } from './group-folder.js';
import { logger } from './logger.js';
import { NewMessage } from './types.js';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface FaqData {
  address?: string;
  payment?: string;
  parking?: string;
}

// ─── CLAUDE.md parser ─────────────────────────────────────────────────────────

/**
 * Reads and parses the ## FAQ section from the group's CLAUDE.md.
 * Returns null if the file doesn't exist or has no FAQ section.
 * Always reads fresh from disk — no caching — so CLAUDE.md updates
 * take effect immediately on the next message.
 */
export function parseFaqFromClaudeMd(groupFolder: string): FaqData | null {
  let groupDir: string;
  try {
    groupDir = resolveGroupFolderPath(groupFolder);
  } catch {
    return null;
  }

  const claudeMdPath = path.join(groupDir, 'CLAUDE.md');
  if (!fs.existsSync(claudeMdPath)) return null;

  let content: string;
  try {
    content = fs.readFileSync(claudeMdPath, 'utf-8');
  } catch (err) {
    logger.warn({ groupFolder, err }, 'faq-shortcircuit: failed to read CLAUDE.md');
    return null;
  }

  // Extract the ## FAQ section (everything until the next ## heading or EOF)
  const faqMatch = content.match(/^## FAQ\s*\n([\s\S]*?)(?=\n## |\s*$)/m);
  if (!faqMatch) return null;

  const section = faqMatch[1];
  const data: FaqData = {};

  // Match the bold-label format generated by tenants.service.ts:
  //   - *Adresă:* Str. Florilor nr. 5, București
  //   - *Plată:* Cash sau card
  //   - *Parcare:* Stradală gratuită
  const addr = section.match(/\*Adres[ăa]:\*\s+(.+)/i);
  if (addr) data.address = addr[1].trim();

  const pay = section.match(/\*Plat[ăa]:\*\s+(.+)/i);
  if (pay) data.payment = pay[1].trim();

  const park = section.match(/\*Parcare:\*\s+(.+)/i);
  if (park) data.parking = park[1].trim();

  return Object.keys(data).length > 0 ? data : null;
}

// ─── Pattern sets ─────────────────────────────────────────────────────────────

/**
 * Booking-intent signals on normalized (diacritic-free) text.
 * If ANY of these match, we pass to the LLM — never short-circuit.
 */
const BOOKING_INTENT: RegExp[] = [
  /\bprogramar/,          // programare, programări
  /\brezervari?\b/,       // rezervare
  /\bvreau\s+sa\b/,       // vreau să
  /\bdisponibil/,
  /\bslot\b/,
  /\bma\s+programez\b/,
  /\bprogramez\b/,
  // Days (diacritic-free)
  /\bluni\b/,
  /\bmarti\b/,
  /\bmiercuri\b/,
  /\bjoi\b/,
  /\bvineri\b/,
  /\bsambata\b/,
  /\bduminica\b/,
  // Time references
  /\bmaine\b/,            // mâine
  /\bazi\b/,
  /\bastazi\b/,           // astăzi
  /\bsaptamana\b/,        // săptămâna
  /\bora\b/,
  /\b\d{1,2}:\d{2}\b/,
  /\bdimineata\b/,
  /\bseara\b/,
  /\bliber[aă]?\b/,       // loc liber
];

/**
 * FAQ trigger patterns → which FaqData key they map to.
 * Matched against normalized (diacritic-free) text.
 */
const FAQ_TRIGGERS: { key: keyof FaqData; patterns: RegExp[] }[] = [
  {
    key: 'address',
    patterns: [
      /\badresa?\b/,
      /\bunde\s+(esti|este|va|sunteti|va\s+gasesc|gasesc|va\s+afla)\b/,
      /\bunde\s+e(sti)?\s+(salonul|frizeria|locatia)\b/,
      /\bcum\s+ajung\b/,
      /\blocati[ei]\b/,
    ],
  },
  {
    key: 'payment',
    patterns: [
      /\bplata?\b/,
      /\bplatesc\b/,
      /\bplatiti\b/,
      /\bcard\b/,
      /\bcash\b/,
      /\bcum\s+pl[ai]t/,
      /\baccept[ai]\b/,
      /\bse\s+poate\s+cu\s+card\b/,
    ],
  },
  {
    key: 'parking',
    patterns: [
      /\bparcare?\b/,
      /\bparchez\b/,
      /\bloc\s+de\s+parcar/,
      /\bunde\s+parchez\b/,
    ],
  },
];

// ─── Core logic ───────────────────────────────────────────────────────────────

function normalize(s: string): string {
  return s
    .toLowerCase()
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .trim();
}

function buildAnswer(key: keyof FaqData, data: FaqData): string {
  switch (key) {
    case 'address':
      return `📍 Adresa noastră: ${data.address}`;
    case 'payment':
      return `💳 Acceptăm: ${data.payment}`;
    case 'parking':
      return `🚗 Parcare: ${data.parking}`;
  }
}

/**
 * Attempts to answer a FAQ question without spawning a container.
 *
 * Returns the answer string if all conditions are met, null otherwise.
 *
 * Conditions (all must hold):
 *   1. Exactly one user message in the batch (not a multi-message thread)
 *   2. Message is short (≤ 300 chars) — long messages are likely complex
 *   3. No booking intent detected
 *   4. A known FAQ pattern matches
 *   5. The matching FAQ field exists in faqData
 */
export function tryFaqShortCircuit(
  messages: NewMessage[],
  faqData: FaqData,
): string | null {
  const userMessages = messages.filter((m) => !m.is_from_me && !m.is_bot_message);
  if (userMessages.length !== 1) return null;

  const raw = userMessages[0].content;
  if (!raw || raw.length > 300) return null;

  const norm = normalize(raw);

  // Never short-circuit if booking intent detected
  if (BOOKING_INTENT.some((re) => re.test(norm))) return null;

  // Check FAQ triggers in order
  for (const { key, patterns } of FAQ_TRIGGERS) {
    if (faqData[key] && patterns.some((re) => re.test(norm))) {
      return buildAnswer(key, faqData);
    }
  }

  return null;
}
